kiss-lint: upd

diff --git a/bin/kiss-lint b/bin/kiss-lint
--- a/bin/kiss-lint
+++ b/bin/kiss-lint
@@ -7,19 +7,19 @@ line_aux() {
 }
 checkposix() {
     # basically search a posix shell script for things that aren't posix
-    (   
+    (
         t="$(grep -nE "sed (-[a-zA-Z]*)*-i?[a-zA-Z]*i[a-zA-Z]*i?" "$f" | line_aux)"
         [ -n "$t" ] && echo "WARNING: 'sed -i' is not portable, use 'sed file > _ ; mv -f _ file' (line(s): $t in $f)"
     ) &
 
-        t="$(grep -v "#" "$f" | grep -nE " ?which " | line_aux)"
-        if [ -n "$t" ]; then
-            echo "WARNING: 'which' is not specified by POSIX, use 'command -v' (lines(s): $t in $f)"
-            fix() {
-                sed -E "s/ ?which / command -v /" >_
-                mv -f _ "$f"
+    t="$(grep -v "#" "$f" | grep -nE " ?which " | line_aux)"
+    if [ -n "$t" ]; then
+        echo "WARNING: 'which' is not specified by POSIX, use 'command -v' (lines(s): $t in $f)"
+        fix() {
+            sed -E "s/ ?which / command -v /" >_
+            mv -f _ "$f"
         }
-            run_autoedit fix
+        run_autoedit fix
     fi
 }
 
@@ -41,7 +41,7 @@ checkpkg() {
                 depends)
                     base="(baseinit|baselayout|busybox|bzip2|git|kiss|make|musl|zlib|xz|pigz)"
                     if grep -qE "^$base" "$f"; then
-                        (   
+                        (
                             t="$(grep -nE "^$base" "$f" | line_aux)"
                             t="$(grep -E "^$base" "$f" | cut -d' ' -f1 | tr '\n' ',' | rev | cut -d',' -f2- | rev) is/are implicit deps (line(s): $t in $f)"
                             echo "WARNING: $t"
@@ -50,74 +50,74 @@ checkpkg() {
 
                     buildtools="(meson|cmake|pkgconf|autoconf|automake)"
                     if grep -qE "^$buildtools$" "$f"; then
-                        (   
+                        (
                             t="$(grep -nE "^$buildtools" "$f" | line_aux)"
                             t="$(grep -E "^$buildtools" "$f" | cut -d' ' -f1 | tr '\n' ',' | rev | cut -d',' -f2- | rev) is/are 'make' deps (line(s): $t in $f)"
                             echo "WARNING: $t"
                         ) &
                     fi
 
-                        if ! [ -s "$f" ]; then
-                            echo "WARNING: '$f' is empty, can be removed"
-                            fix() {
-                                rm -v "$f"
+                    if ! [ -s "$f" ]; then
+                        echo "WARNING: '$f' is empty, can be removed"
+                        fix() {
+                            rm -v "$f"
                         }
-                            run_autoedit fix
+                        run_autoedit fix
                     fi
-                        if ! sort "$f" | diff - "$f" >/dev/null 2>&1; then
-                            echo "STYLE: '$f' is not sorted"
-                            fix() {
-                                sort "$f" >_
-                                mv -f _ "$f"
+                    if ! sort "$f" | diff - "$f" >/dev/null 2>&1; then
+                        echo "STYLE: '$f' is not sorted"
+                        fix() {
+                            sort "$f" >_
+                            mv -f _ "$f"
                         }
-                            run_autoedit fix
+                        run_autoedit fix
                     fi
                     ;;
                 build | post-install | pre-remove)
-                        if ! [ -x "$f" ]; then
-                            echo "ERROR: '$f' not executable"
-                            fix() {
-                                chmod +x "$f"
+                    if ! [ -x "$f" ]; then
+                        echo "ERROR: '$f' not executable"
+                        fix() {
+                            chmod +x "$f"
                         }
-                            run_autoedit fix
+                        run_autoedit fix
                     fi
                     if head -n 1 "$f" | grep -qE "env sh|bin/sh"; then
                         checkposix
-                            t="$(grep -n "mkdir" "$f" | grep -v -- "-p" | line_aux)"
-                            [ -n "$t" ] && echo "WARNING: always use '-p' with 'mkdir' (line(s): $t in $f)"
+                        t="$(grep -n "mkdir" "$f" | grep -v -- "-p" | line_aux)"
+                        [ -n "$t" ] && echo "WARNING: always use '-p' with 'mkdir' (line(s): $t in $f)"
 
                         head -n 1 "$f" | grep -q "sh -e" || echo "ERROR: '$f' is missing the '-e' flag in the shebang" &
 
-                        (   
+                        (
                             t="$(grep -nE "^\ *#\ *[a-z]" "$f" | grep -v "shellcheck" | line_aux)"
                             [ -n "$t" ] && echo "STYLE: '$f' has a comment that starts with a lower case letter (line(s): $t in $f)"
                         ) &
 
                             t=$(grep -n "kiss l" "$f" | grep -v "kiss list" | line_aux)
-                            if [ -n "$t" ]; then
-                                echo "WARNING: use 'kiss list' instead of 'kiss l' (line(s): $t in $f)"
-                                fix() {
-                                    sed "s/kiss l/kiss list/" "$f" >_
-                                    mv -f _ "$f"
+                        if [ -n "$t" ]; then
+                            echo "WARNING: use 'kiss list' instead of 'kiss l' (line(s): $t in $f)"
+                            fix() {
+                                sed "s/kiss l/kiss list/" "$f" >_
+                                mv -f _ "$f"
                             }
-                                run_autoedit fix
+                            run_autoedit fix
                         fi
-                            t=$(grep -n "kiss a" "$f" | grep -v "kiss alternatives" | line_aux)
-                            if [ -n "$t" ]; then
-                                echo "WARNING: use 'kiss alternatives' instead of 'kiss a' (line(s): $t in $f)"
-                                fix() {
-                                    sed "s/kiss a/kiss alternatives/" "$f" >_
-                                    mv -f _ "$f"
+                        t=$(grep -n "kiss a" "$f" | grep -v "kiss alternatives" | line_aux)
+                        if [ -n "$t" ]; then
+                            echo "WARNING: use 'kiss alternatives' instead of 'kiss a' (line(s): $t in $f)"
+                            fix() {
+                                sed "s/kiss a/kiss alternatives/" "$f" >_
+                                mv -f _ "$f"
                             }
-                                run_autoedit fix
+                            run_autoedit fix
                         fi
 
-                        (   
+                        (
                             t="$(fold "$f" | diff - "$f" | grep '>' | sed "s/> //" | while read -r l; do grep -n "$l" build; done | line_aux)"
                             [ -n "$t" ] && echo "STYLE: '$f' has a line(s) that exceed 80 characters (line(s): $t in $f)"
                         ) &
 
-                        (   
+                        (
                             if grep -qE "^\t" "$f"; then
                                 tr -d '\t' <"$f" | diff - "$f" >/dev/null 2>&1 || echo "STYLE: '$f' is using tabs for indentation, use 4 spaces instead" &
                             fi
@@ -128,12 +128,12 @@ checkpkg() {
                     fi
                     ;;
                 sources)
-                        if [ -x "$f" ]; then
-                            echo "WARNING: '$f' is executable"
-                            fix() {
+                    if [ -x "$f" ]; then
+                        echo "WARNING: '$f' is executable"
+                        fix() {
                                 chmod -x "$f"
                         }
-                            run_autoedit fix
+                        run_autoedit fix
                     fi
 
                     [ -n "$VER" ] && {
@@ -151,7 +151,7 @@ checkpkg() {
 
                     grep -qE "(www\.|\.git)" "$f" && echo "STYLE: '$f' drop 'www.' and '.git' if possible" &
 
-                    grep -qE "^http.*patch$" "$f" && echo "STYLE: '$f' avoid remote patches, store them in 'patches/'" &
+                    grep -qE "^http.*(patch|diff)$" "$f" && echo "STYLE: '$f' avoid remote patches, store them in 'patches/'" &
 
                     (grep -E "^(files|patches)/" "$f" | cut -d' ' -f1 | while read -r source_f; do
                         [ -e "$source_f" ] || echo "ERROR: '$source_f' does not exist" &
@@ -182,13 +182,13 @@ esac
 
 if [ $# -gt 1 ]; then
     for d in "$@"; do
-        cd "$d"
+        cd "$d" || exit 1
         printf "\n==> %s <==\n" "$d" # Mimic the output format of `head`.
         checkpkg
-        cd "$OLDPWD"
+        cd "$OLDPWD" || exit 1
     done
     wait
 else
-    [ $# -eq 1 ] && cd "$1"
+    [ $# -eq 1 ] && cd "$1" || exit 1
     checkpkg
 fi
